# Generated by Django 5.0.6 on 2024-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('file_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_info', models.CharField(blank=True, max_length=200, null=True)),
                ('kinship_type', models.CharField(blank=True, max_length=50, null=True)),
                ('complementary_insurance_info', models.CharField(blank=True, max_length=200, null=True)),
                ('referring_info', models.CharField(blank=True, max_length=200, null=True)),
                ('is_foreign_patient', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Patient Card',
                'verbose_name_plural': 'Patient Cards',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
