# Generated by Django 5.0.6 on 2024-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='insured_information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
