# Generated by Django 5.0.6 on 2024-07-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patientcard_insured_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('external_door_no', models.CharField(blank=True, max_length=10, null=True)),
                ('internal_door_no', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('heard_about_us', models.CharField(blank=True, max_length=255, null=True)),
                ('card_issued', models.BooleanField(default=False)),
                ('want_to_be_informed_by_email', models.BooleanField(default=False)),
                ('want_to_be_informed_by_sms', models.BooleanField(default=False)),
                ('want_to_be_informed_by_phone', models.BooleanField(default=False)),
                ('want_to_be_informed_by_post', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_card', to='hospital.patientcard')),
            ],
            options={
                'verbose_name': 'Communication Card',
                'verbose_name_plural': 'Communication Cards',
            },
        ),
        migrations.CreateModel(
            name='PopulationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_number', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_national_id', models.CharField(blank=True, max_length=11, null=True)),
                ('father_national_id', models.CharField(blank=True, max_length=11, null=True)),
                ('declaration', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('registry_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_number', models.CharField(blank=True, max_length=50, null=True)),
                ('family_serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='population_card', to='hospital.patientcard')),
            ],
            options={
                'verbose_name': 'Population Card',
                'verbose_name_plural': 'Population Cards',
            },
        ),
    ]
