# Generated by Django 5.0.6 on 2024-08-25 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_communicationcard_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
