# Generated by Django 5.0.6 on 2024-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patientcard_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.IntegerField(default=0)),
                ('stock_image', models.ImageField(upload_to='images/stock_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
