# Generated by Django 5.0.6 on 2024-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_stock_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
