# Generated by Django 5.0.6 on 2024-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_stock_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_number',
            new_name='stock_buyed',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_image',
        ),
        migrations.AddField(
            model_name='stock',
            name='stcok_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_haved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_pozition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_skt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_ut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_wharehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
