# Generated by Django 5.0.6 on 2024-11-10 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_rename_stock_number_stock_stock_buyed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_number', models.IntegerField(blank=True, default=0, null=True)),
                ('order_wharehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('order_pozition', models.CharField(blank=True, max_length=100, null=True)),
                ('order_group', models.CharField(blank=True, max_length=100, null=True)),
                ('order_startdate', models.DateField(default=django.utils.timezone.now)),
                ('order_finishdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_buyed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_haved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
