# Generated by Django 5.0.6 on 2024-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_order_alter_stock_stock_buyed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_stuation',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
