# Generated by Django 5.0.6 on 2024-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='assignment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Atama Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avg_waiting_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ortalama Hasta Bekleme Süresi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Şehri'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum İlçesi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cüzdan No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='children_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Çocuk Sayısı'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='daily_work',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Günlük Çalışma'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='diploma_date',
            field=models.DateField(blank=True, null=True, verbose_name='Diploma Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='diploma_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diploma No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='diploma_registry_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diploma Tescil No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='doctor_facility_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Doktor Tesis Kodu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='doctor_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doktor Tipi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='duty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Görevi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='duty_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Görev Yeri'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='e_invoice_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-Fatura Hesabı'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='evaluation_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Değerlendirme Grubu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='family_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aile Sıra No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baba Adı'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='foreign_language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yabancı Dil'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_authorized_to_open',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Doçentlik Açabilir Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_candidate_officer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aday Memur Mu?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_company_employee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Firma Elemanı Mı?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_contract_personnel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sözleşmeli Personel Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_convict_personnel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Hükümlü Personel Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_disabled_personnel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Özürlü Personel Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_external_doctor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Dış Doktor Mu?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_foreign_language_support',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Yabancı Dil Yardımı Var Mı?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_intern',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Stajyer Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_retired',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Emekli Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_spouse_working',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Eşi Çalışıyor Mu?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_temporary_personnel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Geçici Personel Mi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_terror_victim',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Terör Mağduru Mu?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Medeni Hal'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='military_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Askerlik Durumu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ana Adı'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C. Kimlik No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uyruğu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Semt'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='neighborhood_village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='next_workplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gittiği Yer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sıra No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='permanence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Asalet Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='personnel_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personel Tipi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası 1'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası 2'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='previous_workplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geldiği Yer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='registry_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sicil No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='retired_registry_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emekli Sicil No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='savings_registry_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tasarruf Sicil No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='seniority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kıdem (Yıl)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='seniority_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kıdem Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='series_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seri Numarası'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='side_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yan Dal'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İmza'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Uzmanlık Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialty_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Uzmanlık Dalı'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialty_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uzmanlık No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sorumlu Kişi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tax_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='union',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sendika'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='union_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sendika No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünite'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='volume_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilt No'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Tipi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/worker_images/'),
        ),
    ]
