# Generated by Django 5.0.6 on 2024-11-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_worker_address_alter_worker_assignment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='İzin Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='İzin Bitiş Tarihi')),
                ('leave_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kullanılan İzin Günleri')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hospital.worker', verbose_name='Çalışan')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Görev')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='İş Tanımı')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Tarih')),
                ('situation', models.CharField(blank=True, max_length=200, null=True, verbose_name='İş Tanımı')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='hospital.worker', verbose_name='Çalışan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='İşbaşı Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Paydos Saati')),
                ('working_days', models.CharField(blank=True, max_length=200, null=True, verbose_name='Çalışma Günleri')),
                ('weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Haftalık Çalışma Saati')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Tarih')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='hospital.worker', verbose_name='Çalışan')),
            ],
        ),
    ]
