# Generated by Django 5.0.6 on 2024-11-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_leave_taskassignment_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='info_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bilgi Notu'),
        ),
        migrations.AddField(
            model_name='worker',
            name='retired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Emeklilik Tarihi'),
        ),
        migrations.CreateModel(
            name='WorkerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/worker_files/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_files', to='hospital.worker', verbose_name='Çalışan')),
            ],
        ),
    ]
