# Generated by Django 5.0.6 on 2024-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_worker_info_note_worker_retired_date_workerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='disability_rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engellilik Oranı'),
        ),
    ]
