# Generated by Django 5.0.6 on 2024-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_worker_disability_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='cheked_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Son Kontrol Eden'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kontrol Tarihi'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='situation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İş Durumu'),
        ),
    ]
