# Generated by Django 5.0.6 on 2024-12-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_patientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wh_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_wharehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.wharehouse'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_wharehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.wharehouse'),
        ),
    ]
