# Generated by Django 5.0.6 on 2024-12-08 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_wharehouse_alter_order_order_wharehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='check_worker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Onaylayan Doktor'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='outofdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='taburcu oldugu tarih'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='patient_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='start_worker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kayıt Acan'),
        ),
    ]
