# Generated by Django 5.0.6 on 2024-12-08 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patientcard_check_worker_patientcard_outofdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcard',
            name='outofdate',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='country',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='sharing_permission',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='smoker',
        ),
        migrations.AddField(
            model_name='patientcard',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discharge Date'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Registration Date'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='sharing_permission',
            field=models.BooleanField(default=False, verbose_name='Sharing Permission'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='abdomen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='chin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hasta Tanısı'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='first_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='İlk Müracaat Tarihi'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='forehead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='graft_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kök Sayısı'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_breast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_cheek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_ear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_eyebrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_hip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_temple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='left_under_eye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_female_1',
            field=models.BooleanField(default=False, verbose_name='Kadın Kellik Seviyesi 1'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_female_2',
            field=models.BooleanField(default=False, verbose_name='Kadın Kellik Seviyesi 2'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_female_3',
            field=models.BooleanField(default=False, verbose_name='Kadın Kellik Seviyesi 3'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_male_1',
            field=models.BooleanField(default=False, verbose_name='Erkek Kellik Seviyesi 1'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_male_2',
            field=models.BooleanField(default=False, verbose_name='Erkek Kellik Seviyesi 2'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_male_3',
            field=models.BooleanField(default=False, verbose_name='Erkek Kellik Seviyesi 3'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_male_4',
            field=models.BooleanField(default=False, verbose_name='Erkek Kellik Seviyesi 4'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='level_male_5',
            field=models.BooleanField(default=False, verbose_name='Erkek Kellik Seviyesi 5'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='lower_lip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Uygulanacak Metod'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='neck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='nose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='note_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='planned_procedure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Uygulanacak Tarih'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='previous_transplant',
            field=models.BooleanField(default=False, verbose_name='Daha Önce Saç Ekimi Yapıldı mı?'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='protocol_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Protokol No'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_breast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_cheek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_ear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_eyebrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_hip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_temple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='right_under_eye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kaçıncı Seans'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='upper_lip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='patient_part',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='hasta bolumu'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Doctor Notes'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='past_surgeries',
            field=models.TextField(blank=True, null=True, verbose_name='Past Surgeries'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='upcoming_surgeries',
            field=models.TextField(blank=True, null=True, verbose_name='Upcoming Surgeries'),
        ),
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/patient_photos/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_photos', to='hospital.patientcard')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, max_length=255, null=True)),
                ('question2', models.CharField(blank=True, max_length=255, null=True)),
                ('question3', models.CharField(blank=True, max_length=255, null=True)),
                ('question4', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_poll', to='hospital.patientcard')),
            ],
        ),
    ]
