# Generated by Django 5.0.6 on 2024-12-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_remove_patientcard_outofdate_remove_patientnote_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_wharehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_orders', to='hospital.wharehouse'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_wharehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_stocks', to='hospital.wharehouse'),
        ),
    ]
