# Generated by Django 5.0.6 on 2024-12-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_order_order_wharehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_check', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='İş Tanımı')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Son Kontrol Tarihi')),
                ('cheked_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Son Kontrol Eden')),
                ('situation', models.CharField(blank=True, max_length=200, null=True, verbose_name='İş Durumu')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checks', to='hospital.taskassignment')),
            ],
        ),
    ]
