# Generated by Django 5.0.6 on 2024-12-13 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_taskcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='flight_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Flight Date'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='is_stranger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='relevant_worker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ilgilenen doktor'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='stayed_hotel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kaldığı Otel'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='tour_operator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tur operatoru'),
        ),
        migrations.CreateModel(
            name='PatientFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/patient_files/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='hospital.patientcard')),
            ],
        ),
    ]
