# Generated by Django 5.0.6 on 2024-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_patientcard_flight_date_patientcard_is_stranger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='cheked_person',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='taskcheck',
            name='situation',
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Görev Yeri'),
        ),
    ]
