# Generated by Django 5.0.6 on 2024-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_remove_taskassignment_cheked_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientnote',
            name='level_female_1',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_female_2',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_female_3',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_male_1',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_male_2',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_male_3',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_male_4',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='level_male_5',
        ),
        migrations.AddField(
            model_name='patientnote',
            name='bold_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kellik seviyesi'),
        ),
    ]
