# Generated by Django 5.0.6 on 2024-12-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_patientfiles_created_at_workerfile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_wharehouse',
            new_name='stock_warehouse',
        ),
    ]
