# Generated by Django 5.0.6 on 2024-12-15 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_rename_wharehouse_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcheck',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son Kontrol Tarihi'),
        ),
    ]
