# Generated by Django 5.0.6 on 2024-12-15 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_alter_taskcheck_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcheck',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son Kontrol Tarihi'),
        ),
    ]
