# Generated by Django 5.0.6 on 2024-12-16 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_alter_patientcard_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='patient_image',
            field=models.FileField(blank=True, null=True, upload_to='images/patient_images/'),
        ),
    ]
