# Generated by Django 5.0.6 on 2024-12-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_alter_patientcard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfiles',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
