# Generated by Django 5.0.6 on 2024-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_alter_patientfiles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='patient_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
