# Generated by Django 5.0.6 on 2024-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_alter_patientcard_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discharge Date'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='flight_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Flight Date'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Date'),
        ),
    ]
