# Generated by Django 5.0.6 on 2024-12-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_alter_patientcard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='patientcard',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='UsedStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_used', models.PositiveIntegerField(default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used_at')),
                ('patient_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_uses', to='hospital.patientcard')),
                ('stock_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_uses', to='hospital.stock')),
            ],
        ),
    ]
