# Generated by Django 5.0.6 on 2024-12-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0040_alter_patientcard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='session_date',
            field=models.DateField(blank=True, null=True, verbose_name='Seans Tarihi'),
        ),
        migrations.AddField(
            model_name='patientcard',
            name='session_time',
            field=models.CharField(blank=True, max_length=29, null=True, verbose_name='Seans Saati'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='consultation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='consultation_date'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='control_1_date',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='control_2_date',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='surgery_date',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/patient_files/'),
        ),
        migrations.AlterField(
            model_name='workerfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/worker_files/'),
        ),
    ]
