import * as yup from "yup"

export const patientFormSchemas = yup.object().shape({
    patient_image: yup.mixed().required('Hasta fotoğrafı seçiniz.'),
    first_name: yup.string().required('"Adı" alanı zorunludur.'),
    last_name: yup.string().required('"Soyadı" alanı zorunludur.'),
    national_id: yup.number().integer().required('"TC/Pasaport" alanı zorunludur.'),
    place_of_birth: yup.string().required('"Doğum Yeri" alanı zorunludur.'),
    date_of_birth: yup.string().required('"Doğum Tarihi" alanı zorunludur.'),
    gender: yup.string().required('"Cinsiyet" alanı zorunludur.'),
    nationality: yup.string().required('"Uyruk" alanı zorunludur.'),
    mother_name: yup.string().required('"Ana Adı" alanı zorunludur.'),
    father_name: yup.string().required('"Baba Adı" alanı zorunludur.'),
    mobile_phone1: yup.number().required('"Cep Telefonu 1" alanı zorunludur.'),
    mobile_phone2: yup.number().required('"Cep Telefonu 2" alanı zorunludur.'),
    email: yup.string().email('Geçerli bir E-Mail giriniz.').required('"Email" alanı zorunludur.'),
    instagram_username: yup.string().required('"İnstagram Adı" alanı zorunludur.'),
    patient_type: yup.string().required('"Hasta Tipi" alanı zorunludur.'),
    country: yup.string().required('"Ülke" alanı zorunludur.'),
    city: yup.string().required('"Şehir" alanı zorunludur.'),
    patient_part: yup.string().required('"Hastanın Bölümü" alanı zorunludur.'),
    relevant_worker: yup.string().required('"Doktor Adı" alanı zorunludur.'),
    address: yup.string().required('"İkametgah Adresi" alanı zorunludur.'),
    //check_worker: yup.string().required("*"),


    seans_number: yup.number().required("*"),
    device_name: yup.string().required("*"),
    education_status: yup.string().required("*"),
    occupation: yup.string().required("*"),
    current_employer: yup.string().required("*"),
    marital_status: yup.string().required("*"),
    children_count: yup.number().integer().required("*"),
    referee: yup.string().required("*"),
    institution_type: yup.string().required("*"),
    applied_department: yup.string().required("*"),
    applied_operation: yup.string().required("*"),
    insurance_info: yup.string().required("*"),
    complaints: yup.string().required("*"),
    medications: yup.string().required("*"),
    existing_conditions: yup.string().required("*"),
    past_surgeries: yup.string().required("*"),
    allergies: yup.string().required("*"),
    post_surgery_address: yup.string().required("*"),
    
})